# .github/workflows/deploy.yml
name: Deploy to Vercel

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Allow manual triggers

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Verify Farcaster requirements
        run: |
          echo "Checking Farcaster Mini App requirements..."
          
          # Check if required files exist
          if [ -f ".well-known/farcaster.json" ]; then
            echo "✅ Farcaster manifest found"
            cat .well-known/farcaster.json
          else
            echo "❌ .well-known/farcaster.json not found - required for Farcaster Mini Apps"
            exit 1
          fi
          
          if [ -f "vercel.json" ]; then
            echo "✅ Vercel config found"
            cat vercel.json
          else
            echo "⚠️  vercel.json not found - recommended for proper routing"
          fi
          
          if [ -f "index.html" ]; then
            echo "✅ index.html found"
            # Check for required meta tags
            if grep -q "fc:miniapp" index.html; then
              echo "✅ Farcaster miniapp meta tag found"
            else
              echo "⚠️  fc:miniapp meta tag missing from index.html"
            fi
            if grep -q "fc:frame:manifest" index.html; then
              echo "✅ Farcaster manifest meta tag found"
            else
              echo "⚠️  fc:frame:manifest meta tag missing from index.html"
            fi
          else
            echo "❌ index.html not found"
            exit 1
          fi
          
          if [ -f "assets/icon.svg" ]; then
            echo "✅ Icon found"
          else
            echo "⚠️  assets/icon.svg not found - referenced in manifest"
          fi
      
      - name: Install Vercel CLI
        run: npm i -g vercel@latest
      
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
        
      - name: Verify deployment
        run: |
          echo "🚀 Deployment complete!"
          echo "📱 Your Farcaster Mini App: https://bitcoin-tx-battle-farcaster.vercel.app/"
          echo "🔧 Farcaster manifest: https://bitcoin-tx-battle-farcaster.vercel.app/.well-known/farcaster.json"
          echo ""
          echo "Next steps:"
          echo "1. Test the manifest URL above"
          echo "2. Ensure you've updated your Farcaster FID in the manifest"
          echo "3. Enable developer mode in Farcaster"
          echo "4. Test your Mini App in Farcaster"
